### PR TITLE
Add a few of basic tests for LoginPage component

### PR DESCRIPTION
**Pull request by jihchi**
# Why

To demonstrate how to write tests using current tech stack:
1. Unit test is executed by Jest (`react-scripts` built-in).
1. Use `@testing-library/react` to render  React component.
1. Use `@testing-library/user-event` to interactive with the component.

# How

```
npm test
# or
yarn test
```

# References

1. https://jestjs.io/
1. https://create-react-app.dev/docs/running-tests#react-testing-library
1. https://testing-library.com/docs/react-testing-library/intro/
1. https://testing-library.com/docs/ecosystem-user-event

### CODE REVIEW

**Comment by chhsiao1981** [comment]
hi @jihchi ～

Not exactly sure whether it's ok～
I saw the following error:

image

    Warning: An update to _default inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at _default (/Users/chhsiao/projects/demo-pttbbs/src/components/LoginPage.js:15:41)

**Comment by jihchi** [comment]
I'm aware of this warning but I think it is fine to leave it as it is for now.

You can see that the warning is caused by the library [`react-reducer-utils`](https://github.com/chhsiao1981/react-reducer-utils):
```jsx
...
    at _default (/Users/chhsiao/projects/demo-pttbbs/src/components/LoginPage.js:15:41)
...
```

**Comment by solring** [comment]
I also encountered that warning when trying testing framework myself.
The warning will disappear if you put all the renders inside that act function.
So is it actually unnecessary to follow their guidelines?

Thanks in advance.

**Comment by chhsiao1981** [comment]
@jihchi and @solring 

I'll pass this one first, and then we can have another PR fixing the warning with act().

**Pull request merged**
